# Generated by Django 2.2.1 on 2019-07-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('time', models.TimeField(auto_now=True)),
                ('status', models.CharField(default='deactive', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='abcd.jpg', upload_to='profile')),
                ('about', models.TextField()),
                ('gender', models.CharField(default='gender', max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('marrigestaus', models.CharField(default='never', max_length=100)),
                ('cover', models.ImageField(default='cover.jpg', upload_to='cover')),
                ('status', models.CharField(default='active', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Users')),
            ],
        ),
    ]
